# Header
menu:
  Home: /
  Blog: /blog/archives
  About: /about
  Photos: /photos
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-40684400-1
favicon: true
twitter: takeshik
google_plus: TakeshiKiriya26
fb_admins: 100000020754195
fb_app_id: 1526833280913323
