# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/tommy351
rss: /atom.xml
banner: images/mesh_fencing-wallpaper-1600x900.jpg

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5

# Sidebar
sidebar: false
widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: "monthly"
show_count: false

# Miscellaneous
google_analytics: UA-4910098-7
gauges_analytics:
favicon: /favicon.png
twitter: tommy351
fb_admins: 100000247608790
fb_app_id:
